### ISSUE TITLE
Currying & partial application

### ISSUE THREAD

**Issue by rpearce** [articulate/funky#24]
I know this is an issue writ large and thought we could track the solving of it here. It trips me up from time to time, so I'd like to solve it.

## The Issue
This issue cropped up most recently on https://github.com/articulate/funky/pull/20. The short version is that the way we say a number of functions work in the API docs is not quite how they work:

Docs:
```js
combine(always({ foo: 1 }), { foo: 2, bar: 3 }) //=> { foo: 1, baz: 3 }
```

Reality:
```js
combine(always({ foo: 1 }), { foo: 2, bar: 3 }) //=> Function
combine(always({ foo: 1 }))({ foo: 2, bar: 3 }) //=> { foo: 1, baz: 3 }
```

## Which Way to Go?
* pulling in [`crocks`](https://github.com/evilsoft/crocks) to get at its `curry` has been said to not desired
* @mgreystone mentioned using ramda's [`uncurryN`](https://ramdajs.com/docs/#uncurryN)
  * Q: What would something like [`combineAllP`](https://github.com/articulate/funky/blob/master/src/combineAllP.js) look like using `uncurryN`?
* there is the manual way of doing it like in https://github.com/articulate/funky/blob/master/src/assocWith.js#L7-L8 where we are not pointfree

**Comment by rpearce** [comment]
cc @flintinatux @pklingem

**Comment by mgreystone** [comment]
[Working](https://ramdajs.com/repl/#?const%20juxtP%20%3D%20uncurryN%282%2C%20fns%20%3D%3E%0A%20%20compose%28Promise.all.bind%28Promise%29%2C%20juxt%28fns%29%29%0A%29%0A%0Aconst%20combineAllP%20%3D%20uncurryN%282%2C%20fns%20%3D%3E%0A%20%20composeP%28mergeAll%2C%20juxtP%28%5B%20identity%2C%20...fns%20%5D%29%29%0A%29%0A%0AcombineAllP%28%0A%20%20%5B%20always%28%7B%20foo%3A%201%20%7D%29%2C%20always%28%7B%20bar%3A%202%20%7D%29%5D%2C%0A%20%20%7B%20baz%3A%203%20%7D%2C%0A%29.then%28console.log%29)

**Comment by evilsoft** [comment]
Yeppers, without crocks, I would say `R.uncurryN` is the way to go!

**Comment by rpearce** [comment]
Thanks for clarifying, @mgreystone; good stuff and simple. Ty for the thoughts, @evilsoft. Curious what the others think between the two, as well

**Comment by evilsoft** [comment]
We have a couple more things to do, but this will come with `@crocksjs/helpers` when we have 1.0. But in the mean time,I think the `uncurryN` is the way to go.

The whole reason for the API change we are doing with the `@crocksjs` is so libs can grab what they want a la carte. Soon my friend, soon!

**Comment by rpearce** [comment]
Got it. Thanks, gents

**Comment by rpearce** [comment]
(update: working on this as of today)
