### ISSUE TITLE
Curried Function Lengths Are Wrong

### ISSUE THREAD

**Issue by mgreystone** [articulate/funky#34]
The use of `uncurryN` is causing functions to return with incorrect lengths. See #26 .

Examples:
```js
const arity2 = (a, b) => {}

// In funky 1.3.1, these all have a length of 2
// In funky 1.4.2, these all have a length of 1
combineAll([ arity2 ]).length
combineAllP([ arity2 ]).length
combineWith(merge, arity2).length
```

Options:
1. Force all returning functions to be unary functions.
1. Follow the "ramda" pattern to force function lengths to be evaluated during compositon. 
    In other words, remove auto curry. Force `combineAll(arr)(data)` & drop support for `combineAll(arr, data)`. Ramda does not allow `juxt(arr, data)` for this exact reason.
1. Attempt to apply auto curry magic. https://github.com/articulate/funky/pull/35

**Comment by rpearce** [comment]
If #3 creates more trouble than it's worth, I am ok with #2 and living with that

**Comment by mgreystone** [comment]
My vote [continues to be](https://github.com/articulate/funky/pull/21#issuecomment-422515792) for option 2. I'm not interested in taking #35 any further, but @rpearce (or anyone) please feel free to bang on it.

**Comment by rpearce** [comment]
I'm with you, then. @flintinatux: any opinions?

**Comment by flintinatux** [comment]
Depends on which convention we want to follow.  I intentionally decided to make `tinyfunk` only support unary functions, partially for this reason, and partially because it makes the code so much simpler.  But `ramda` tries to support all-the-things.  If that's us too, then it's ok to follow the same patterns as `ramda`.
